//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNHB.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppliedTagQuestion
    {
        public int QuestionId { get; set; }
        public int TagId { get; set; }
        public System.DateTime AppliedDate { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
