//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNHB.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string Content { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int ArticleId { get; set; }
        public int UserId { get; set; }
        public bool isActive { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
