//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNHB.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventCalendar
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public int UserID { get; set; }
        public System.DateTime DateTimeScheduled { get; set; }
        public int StatusENUM { get; set; }
        public System.DateTime EndDay { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public bool IsActive { get; set; }
    }
}
