//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNHB.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int Id { get; set; }
        public string ImagePath { get; set; }
        public string ImageSmallPath { get; set; }
        public Nullable<int> PlaceId { get; set; }
        public Nullable<int> ReviewId { get; set; }
    
        public virtual Place Place { get; set; }
        public virtual Review Review { get; set; }
    }
}
